#include <iostream>
#include <windows.h>
#include <TlHelp32.h>
#include <vector>
#include <d3dx9math.h>
#pragma comment(lib, "d3dx9.lib")
#include <algorithm>
#define _USE_MATH_DEFINES
#include <math.h>
#include <ctime>
#include <map>
#include <Psapi.h>
#include <urlmon.h>
#include <iomanip> 
#include <wininet.h>
#include <codecvt>
#include <cstdint>
#include <stdio.h>
#include <fstream>
#include <emmintrin.h>